# Generated by Django 5.1.5 on 2025-04-02 09:59

# import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_playlist_video'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='blog',
        #     name='content',
        #     field=ckeditor.fields.RichTextField(blank=True, null=True),
        # ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogComment', to='content.blog')),
            ],
        ),
    ]
