# Generated by Django 5.1.5 on 2025-04-03 17:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_blog_content_blogcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('parents_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='students/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('Reg_no', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('designation', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=80)),
                ('phone_no', models.CharField(max_length=12)),
                ('photo', models.ImageField(upload_to='volunteer/')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
