# Generated by Django 5.1.5 on 2025-04-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_student_address_student_grade_student_prev_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='photo',
            field=models.ImageField(null=True, upload_to='volunteer/'),
        ),
    ]
