# Generated by Django 5.1.5 on 2025-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewVolunteer',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('phoneNo', models.CharField(max_length=12)),
                ('interestArea', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
    ]
