# Generated by Django 5.1.5 on 2025-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pahal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('phoneNo', models.CharField(max_length=12)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
